%% BMS_DCDC_Core_SelfTest
% BMS-DCDC 管理算法核心函数自检。
% 该脚本不依赖 Simulink，可用于快速验证 V1.0 主要需求逻辑。

BMS_DCDC_Params;

fprintf('Running BMS-DCDC core self-tests...\n');

%% TC02：放电时 SOC 高的簇多出力
[EnableCmd, ModeCmd, Pwr, Cur, ~, ~, ~, ~, ~, ~] = ...
    BMS_DCDC_Manager_Core(true, 300.0, uint8(4), 2.0, ...
    [90.0, 60.0, 30.0, 75.0], [100.0, 100.0, 100.0, 100.0], ...
    [750.0, 750.0, 750.0, 750.0], [35.0, 35.0, 35.0, 35.0], ...
    [false, false, false, false], [true, true, true, true], ...
    [false, false, false, false], [200.0, 200.0, 200.0, 200.0], ...
    [200.0, 200.0, 200.0, 200.0]);

assert(all(EnableCmd), 'TC02 failed: all healthy discharge clusters should be enabled.');
assert(all(ModeCmd == uint8(2)), 'TC02 failed: all healthy clusters should be in discharge mode.');
assert(Pwr(1) > Pwr(4) && Pwr(4) > Pwr(2) && Pwr(2) > Pwr(3), ...
    'TC02 failed: discharge power should follow SOC order.');
assert(all(Cur > 0.0), 'TC02 failed: target current should be positive.');

%% TC03：充电时 SOC 低的簇多充电
[~, ModeCmd, Pwr, ~, ChgLim, DisLim, Stop, ~, ~, ~] = ...
    BMS_DCDC_Manager_Core(true, -300.0, uint8(4), 2.0, ...
    [90.0, 60.0, 30.0, 75.0], [100.0, 100.0, 100.0, 100.0], ...
    [750.0, 750.0, 750.0, 750.0], [35.0, 35.0, 35.0, 35.0], ...
    [false, false, false, false], [true, true, true, true], ...
    [false, false, false, false], [200.0, 200.0, 200.0, 200.0], ...
    [200.0, 200.0, 200.0, 200.0]);

assert(all(ModeCmd == uint8(1)), 'TC03 failed: all healthy clusters should be in charge mode.');
assert(abs(Pwr(3)) > abs(Pwr(2)) && abs(Pwr(2)) > abs(Pwr(4)) && abs(Pwr(4)) > abs(Pwr(1)), ...
    'TC03 failed: charge power should be larger for lower SOC.');
assert(all(Pwr < 0.0), 'TC03 failed: charge target power should be negative.');
assert(all(ChgLim > 0.0) && all(DisLim == 0.0), 'TC03 failed: charge mode limits are incorrect.');
assert(all(Stop == uint16(0)), 'TC03 failed: healthy clusters should not report stop reasons.');

%% TC01：故障簇退出
[EnableCmd, ModeCmd, Pwr, Cur, ChgLim, DisLim, Stop, ~, ~, ~] = ...
    BMS_DCDC_Manager_Core(true, 300.0, uint8(4), 2.0, ...
    SOC, SOH, ClusterVoltage, MaxTemperature, ...
    [false, true, false, false], DCDCCommOK, DCDCCommTimeout, ...
    RatedChargeCurrent, RatedDischargeCurrent);

assert(~EnableCmd(2), 'TC01 failed: fault cluster should be disabled.');
assert(ModeCmd(2) == uint8(3), 'TC01 failed: fault cluster should be in fault mode.');
assert(Pwr(2) == 0.0 && Cur(2) == 0.0, 'TC01 failed: fault cluster targets should be zero.');
assert(ChgLim(2) == 0.0 && DisLim(2) == 0.0, 'TC01 failed: fault cluster limits should be zero.');
assert(Stop(2) == uint16(2), 'TC01 failed: fault stop reason should be CLUSTER_FAULT.');

%% TC06：通信超时停机
[EnableCmd, ModeCmd, Pwr, Cur, ~, ~, Stop, ~, ~, ~] = ...
    BMS_DCDC_Manager_Core(true, 300.0, uint8(4), 2.0, ...
    SOC, SOH, ClusterVoltage, MaxTemperature, FaultStatus, ...
    DCDCCommOK, [false, true, false, false], ...
    RatedChargeCurrent, RatedDischargeCurrent);

assert(~EnableCmd(2), 'TC06 failed: timeout cluster should be disabled.');
assert(ModeCmd(2) == uint8(3), 'TC06 failed: timeout cluster should be in fault mode.');
assert(Pwr(2) == 0.0 && Cur(2) == 0.0, 'TC06 failed: timeout cluster targets should be zero.');
assert(Stop(2) == uint16(3), 'TC06 failed: timeout stop reason should be DCDC_COMM_TIMEOUT.');

%% TC07：系统待机
[EnableCmd, ModeCmd, Pwr, Cur, ChgLim, DisLim, Stop, ~, AvChg, AvDis] = ...
    BMS_DCDC_Manager_Core(true, 0.0, uint8(4), 2.0, ...
    SOC, SOH, ClusterVoltage, MaxTemperature, FaultStatus, ...
    DCDCCommOK, DCDCCommTimeout, RatedChargeCurrent, RatedDischargeCurrent);

assert(all(~EnableCmd), 'TC07 failed: standby should disable all clusters.');
assert(all(ModeCmd == uint8(0)), 'TC07 failed: standby mode command expected.');
assert(all(Pwr == 0.0) && all(Cur == 0.0), 'TC07 failed: standby targets should be zero.');
assert(all(ChgLim == 0.0) && all(DisLim == 0.0), 'TC07 failed: standby limits should be zero.');
assert(all(AvChg == 0.0) && all(AvDis == 0.0), 'TC07 failed: standby available power should be zero.');
assert(all(Stop == uint16(0)), 'TC07 failed: standby with healthy clusters should not report stop reasons.');

%% TC08：无可用簇
[EnableCmd, ModeCmd, Pwr, Cur, ChgLim, DisLim, Stop, Limit, AvChg, AvDis] = ...
    BMS_DCDC_Manager_Core(true, 300.0, uint8(4), 2.0, ...
    SOC, SOH, ClusterVoltage, [65.0, 65.0, 65.0, 65.0], ...
    FaultStatus, DCDCCommOK, DCDCCommTimeout, RatedChargeCurrent, RatedDischargeCurrent);

assert(all(~EnableCmd), 'TC08 failed: no available power should disable all clusters.');
assert(all(ModeCmd == uint8(0)), 'TC08 failed: no available power should stay in standby.');
assert(all(Pwr == 0.0) && all(Cur == 0.0), 'TC08 failed: no available power targets should be zero.');
assert(all(ChgLim == 0.0) && all(DisLim == 0.0), 'TC08 failed: no available power limits should be zero.');
assert(all(AvChg == 0.0) && all(AvDis == 0.0), 'TC08 failed: no available power debug outputs should be zero.');
assert(all(Stop == uint16(6)), 'TC08 failed: no available power stop reason expected.');
assert(all(Limit == uint16(0)), 'TC08 failed: no available power should clear output limit reasons.');

fprintf('All BMS-DCDC core self-tests passed.\n');
