%% build_BMS_DCDC_Manager_V1
% 自动搭建 BMS_DCDC_Manager_V1.slx。
% 运行前请确认当前目录包含 BMS_DCDC_Params.m 和 BMS_DCDC_Manager_Core.m。

modelName = 'BMS_DCDC_Manager_V1';

BMS_DCDC_Params;
BMS_DCDC_BusDef;

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

if exist([modelName '.slx'], 'file') == 4
    delete([modelName '.slx']);
end

new_system(modelName);
open_system(modelName);

set_param(modelName, ...
    'StopTime', '1', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.1', ...
    'SaveFormat', 'StructureWithTime');

%% 顶层中文备注
addModelAnnotation(modelName, [30 20 880 95], ...
    sprintf(['BMS-DCDC 管理算法 V1.0\n', ...
    '固定支持 4 个电池簇；正功率表示放电，负功率表示充电。\n', ...
    '严重故障、通信异常、通信超时、系统停机和电压无效时，对应簇 DCDC 停机并清零目标值。']));

addModelAnnotation(modelName, [30 590 880 670], ...
    sprintf(['中文备注：信号名保持英文，便于代码生成和协议对接。\n', ...
    '核心算法集中在 MATLAB Function Block，后续可按需求拆分为有效性检查、温度降额、SOH 降额、功率分配和命令生成子模块。']));

%% 文档化顶层区域
add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Scenario_Source'], ...
    'Position', [30 125 185 225]);
add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Input_Bus_Builder'], ...
    'Position', [30 255 185 355]);
add_block('simulink/Ports & Subsystems/Subsystem', [modelName '/Output_Bus_Builder'], ...
    'Position', [700 255 875 355]);

clearDefaultSubsystem([modelName '/Scenario_Source']);
clearDefaultSubsystem([modelName '/Input_Bus_Builder']);
clearDefaultSubsystem([modelName '/Output_Bus_Builder']);

addSubsystemAnnotation([modelName '/Scenario_Source'], [20 25 360 120], ...
    sprintf(['测试激励 / Scenario_Source\n', ...
    '默认场景数据来自 BMS_DCDC_Params.m。\n', ...
    'TC01~TC08 可在自检脚本和后续测试模型中扩展。']));
addSubsystemAnnotation([modelName '/Input_Bus_Builder'], [20 25 370 120], ...
    sprintf(['输入接口说明\n', ...
    '系统级输入：SystemRunCmd、SystemTargetPower、NumClusters、MinRunCurrent。\n', ...
    '簇级数组固定 4 维：SOC、SOH、电压、温度、故障、通信和额定电流。']));
addSubsystemAnnotation([modelName '/Output_Bus_Builder'], [20 25 390 140], ...
    sprintf(['输出接口说明\n', ...
    'DCDCEnableCmd：启停命令。\n', ...
    'DCDCModeCmd：0=待机，1=充电，2=放电，3=故障。\n', ...
    'TargetCurrent 始终为正值，方向由模式命令区分。']));

%% 核心 MATLAB Function Block
corePath = [modelName '/BMS_DCDC_Manager_Core'];
add_block('simulink/User-Defined Functions/MATLAB Function', corePath, ...
    'Position', [390 235 590 390]);

setMatlabFunctionScript(modelName, corePath);

%% 顶层输入输出端口
inputDefs = { ...
    'SystemRunCmd', 'boolean', '1'; ...
    'SystemTargetPower', 'double', '1'; ...
    'NumClusters', 'uint8', '1'; ...
    'MinRunCurrent', 'double', '1'; ...
    'SOC', 'double', '4'; ...
    'SOH', 'double', '4'; ...
    'ClusterVoltage', 'double', '4'; ...
    'MaxTemperature', 'double', '4'; ...
    'FaultStatus', 'boolean', '4'; ...
    'DCDCCommOK', 'boolean', '4'; ...
    'DCDCCommTimeout', 'boolean', '4'; ...
    'RatedChargeCurrent', 'double', '4'; ...
    'RatedDischargeCurrent', 'double', '4'};

outputDefs = { ...
    'DCDCEnableCmd', 'boolean', '4'; ...
    'DCDCModeCmd', 'uint8', '4'; ...
    'TargetPower', 'double', '4'; ...
    'TargetCurrent', 'double', '4'; ...
    'ChargeCurrentLimit', 'double', '4'; ...
    'DischargeCurrentLimit', 'double', '4'; ...
    'StopReason', 'uint16', '4'; ...
    'LimitReason', 'uint16', '4'; ...
    'AvailableChargePower', 'double', '4'; ...
    'AvailableDischargePower', 'double', '4'};

for idx = 1:size(inputDefs, 1)
    y = 120 + idx * 32;
    blockPath = [modelName '/' inputDefs{idx, 1}];
    add_block('simulink/Sources/In1', blockPath, 'Position', [230 y 260 y+14]);
    set_param(blockPath, 'OutDataTypeStr', inputDefs{idx, 2}, 'PortDimensions', inputDefs{idx, 3});
end

for idx = 1:size(outputDefs, 1)
    y = 145 + idx * 32;
    blockPath = [modelName '/' outputDefs{idx, 1}];
    add_block('simulink/Sinks/Out1', blockPath, 'Position', [720 y 750 y+14]);
    set_param(blockPath, 'OutDataTypeStr', outputDefs{idx, 2}, 'PortDimensions', outputDefs{idx, 3});
end

set_param(modelName, 'SimulationCommand', 'Update');

for idx = 1:size(inputDefs, 1)
    add_line(modelName, [inputDefs{idx, 1} '/1'], ['BMS_DCDC_Manager_Core/' num2str(idx)], 'autorouting', 'on');
end

for idx = 1:size(outputDefs, 1)
    add_line(modelName, ['BMS_DCDC_Manager_Core/' num2str(idx)], [outputDefs{idx, 1} '/1'], 'autorouting', 'on');
end

%% 核心算法中文备注
addModelAnnotation(modelName, [365 420 630 535], ...
    sprintf(['核心算法说明\n', ...
    '1. 先判断簇有效性和停机原因。\n', ...
    '2. 按温度和 SOH 计算限流系数。\n', ...
    '3. 放电按 SOC 权重分配，充电按 100-SOC 权重分配。\n', ...
    '4. 目标功率受可用功率限制，目标电流 = abs(功率)*1000/电压。']));

addModelAnnotation(modelName, [690 390 930 535], ...
    sprintf(['原因码摘要\n', ...
    'StopReason: 0无、1系统停机、2簇故障、3通信超时、4通信异常、5电压无效、6无可用功率。\n', ...
    'LimitReason: 0无、1温度限流、2 SOH限流、3温度和SOH共同限流。']));

save_system(modelName);
fprintf('Generated %s.slx in %s\n', modelName, pwd);

%% Local helper functions
function clearDefaultSubsystem(subsystemPath)
blocks = find_system(subsystemPath, 'SearchDepth', 1, 'Type', 'Block');
for idx = 1:numel(blocks)
    if ~strcmp(blocks{idx}, subsystemPath)
        delete_block(blocks{idx});
    end
end
lines = find_system(subsystemPath, 'SearchDepth', 1, 'FindAll', 'on', 'Type', 'Line');
for idx = 1:numel(lines)
    delete_line(lines(idx));
end
end

function addModelAnnotation(modelName, position, text)
try
    note = Simulink.Annotation(modelName, text);
    note.Position = position;
catch
    fprintf('Annotation skipped: %s\n', text);
end
end

function addSubsystemAnnotation(subsystemPath, position, text)
try
    note = Simulink.Annotation(subsystemPath, text);
    note.Position = position;
catch
    fprintf('Subsystem annotation skipped: %s\n', subsystemPath);
end
end

function setMatlabFunctionScript(modelName, corePath)
scriptText = [
    "function [DCDCEnableCmd, DCDCModeCmd, TargetPower, TargetCurrent, ...", newline, ...
    "    ChargeCurrentLimit, DischargeCurrentLimit, StopReason, LimitReason, ...", newline, ...
    "    AvailableChargePower, AvailableDischargePower] = fcn(SystemRunCmd, SystemTargetPower, NumClusters, MinRunCurrent, ...", newline, ...
    "    SOC, SOH, ClusterVoltage, MaxTemperature, FaultStatus, DCDCCommOK, DCDCCommTimeout, RatedChargeCurrent, RatedDischargeCurrent)", newline, ...
    "%#codegen", newline, ...
    "% BMS-DCDC 管理算法 V1.0：调用根目录核心函数。", newline, ...
    "% 中文备注：模型固定 4 个簇，簇级输入输出均为 4 维数组。", newline, ...
    "[DCDCEnableCmd, DCDCModeCmd, TargetPower, TargetCurrent, ...", newline, ...
    "    ChargeCurrentLimit, DischargeCurrentLimit, StopReason, LimitReason, ...", newline, ...
    "    AvailableChargePower, AvailableDischargePower] = ...", newline, ...
    "    BMS_DCDC_Manager_Core(SystemRunCmd, SystemTargetPower, NumClusters, MinRunCurrent, ...", newline, ...
    "    SOC, SOH, ClusterVoltage, MaxTemperature, FaultStatus, ...", newline, ...
    "    DCDCCommOK, DCDCCommTimeout, RatedChargeCurrent, RatedDischargeCurrent);", newline, ...
    "end"];

set_param(modelName, 'SimulationCommand', 'Update');
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', corePath);
if isempty(chart)
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Name', 'BMS_DCDC_Manager_Core');
end
if isempty(chart)
    error('Cannot find MATLAB Function chart for %s.', corePath);
end
chart.Script = char(scriptText);
set_param(modelName, 'SimulationCommand', 'Update');
end
